# This pipeline is purely for gavel documentation

image: node:10-alpine

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build-docs:
  stage: build
  script:
    - npm install -g yarn
    - yarn
    - yarn build
  cache:
    key: $CI_JOB_NAME
    paths:
      - node_modules/
  artifacts:
    paths:
      - docs/.vuepress/dist
    expire_in: 7 days

deploy-docs:
  image: python:alpine
  stage: deploy
  dependencies:
    - build-docs
  script:
    - pip install awscli
    - aws s3 sync docs/.vuepress/dist/ s3://$S3_BUCKET_PRODUCTION/ --include "*" --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_PRODUCTION_ID --paths "/*"
    - echo "Documentation deployed to production environment"
  only:
    - master
  environment:
    name: Documentation
    url: $PRODUCTION_URL
